### PR TITLE
Fix the build with mtl-2.3

### LINKED ISSUE #61: Build failure with mtl-2.3
```
Building library for stache-2.3.1..
[1 of 6] Compiling Text.Mustache.Type ( Text/Mustache/Type.hs, dist/build/Text/Mustache/Type.o, dist/build/Text/Mustache/Type.dyn_o )
[2 of 6] Compiling Text.Mustache.Render ( Text/Mustache/Render.hs, dist/build/Text/Mustache/Render.o, dist/build/Text/Mustache/Render.dyn_o )

Text/Mustache/Render.hs:89:5: error:
    Variable not in scope: unless :: Bool -> Render () -> Render ()
   |
89 |     unless (isBlank val) $
   |     ^^^^^^

Text/Mustache/Render.hs:92:11: error:
    • Variable not in scope:
        forM_ :: [Value] -> (Value -> Render ()) -> Render ()
    • Perhaps you meant one of these:
        ‘V.forM_’ (imported from Data.Vector),
        ‘V.forM’ (imported from Data.Vector),
        ‘V.iforM_’ (imported from Data.Vector)
      Perhaps you want to add ‘forM_’ to the import list in the import of
      ‘Data.Foldable’ (Text/Mustache/Render.hs:26:1-27).
   |
92 |           forM_ (V.toList xs) $ \x ->
   |           ^^^^^

Text/Mustache/Render.hs:98:3: error:
    Variable not in scope:
      when :: Bool -> Render () -> ReaderT RenderContext (State S) ()
   |
98 |   when (isBlank val) $
   |   ^^^^
```

### PR DESCRIPTION
**Pull request by mrkkrp**
Close #61.

### CODE REVIEW

**Review by sestrella — APPROVED** [review]

**Comment by sestrella** [comment]
Thank you
